[phases.setup]
nixPkgs = ["python312"]

[phases.install]
commands = [
  "pip install -r BetChecker-BackEnd/requirements.txt"
]

[start]
command = "cd BetChecker-BackEnd && uvicorn app.main:app --host 0.0.0.0 --port $PORT"


